### ISSUE TITLE
bug: cannot cleanup fragment in `onDestroyView()`

### ISSUE THREAD

**Issue by or-dvir** [Zhuinden/fragmentviewbindingdelegate-kt#12]
i am using this library with a `RecyclerView`, and i need to cleanup resources in `onDestroyView()`.
in order to prevent a memory leak i need to do this:
```
override fun onDestroyView() {
        binding.recyclerView.adapter = null
        super.onDestroyView()
    }
```

but i get an error: `java.lang.IllegalStateException: Should not attempt to get bindings when Fragment views are destroyed.`

i did a quick google search and found [this](https://proandroiddev.com/make-android-view-binding-great-with-kotlin-b71dd9c87719) article where this very problem is described and solved in [this section](https://proandroiddev.com/make-android-view-binding-great-with-kotlin-b71dd9c87719#e8bc) (link may not work 100%, the section is "Something went wrong").

please add this to your library :)

**Comment by Zhuinden** [comment]
It should be

``` kotlin
override fun onViewCreated(view: View, savedInstanceState: Bundle) {
    super.onViewCreated(view, savedInstanceState)
    val binding = binding

    viewLifecycleOwner.lifecycle.addObserver(object: DefaultLifecycleObserver {
        override fun onDestroy(owner: LifecycleOwner) {
            // clean up here
        }
    })
}
```

as such, it's not a responsibility of the delegate.

You could even do

``` kotlin
inline fun LifecycleOwner.observeOnDestroy(crossinline action: () -> Unit) {
    lifecycle.addObserver(object: DefaultLifecycleObserver {
        override fun onDestroy(owner: LifecycleOwner) {
            action()
        }
    })
}
```

And you'd be like

``` kotlin
val binding = binding

viewLifecycleOwner.observeOnDestroy {
    binding.recyclerView.adapter = null
}
```

So I'm not sure if any change really is needed from my side.

**Comment by or-dvir** [comment]
i see that you have a pull request that is supposed to fix this issue. that would be nice.

please let me know (by commenting on this issue) if this issue is resolved (or not, so i konw i need to do this myself)

**Comment by ChristopherME** [comment]
I think it is not the library responsibility to fix this. This is a known "bug" with the recyclerview. try this: https://gist.github.com/ChristopherME/82d34b68b8b4d0968ff4ebb6b379afec

Also see this: https://www.reddit.com/r/androiddev/comments/ljwltx/recyclerview_adapter_memory_leak/

**Comment by or-dvir** [comment]
@ChristopherME and yet there is a pull request that is supposed to fix this. what is the status in terms of merging this pull request?

**Comment by osgu** [comment]
So, I had some issues with this aswell. I really love the way this code "solves" viewbinding. This can happen in several cases, for me it was if an animation was running and in the end it tried to change something but the view had been backed out of (destroyed). Same for some other places with different things able to happen.

So instead of returning ViewBinding, I return ViewBinding?

That way you are forced to handle cases when its null and I went from quite alot of crashes in production to 0.

```
fun <T : ViewBinding> Fragment.viewBinding(viewBindingFactory: (View) -> T?) =
    FragmentViewBindingDelegate(this, viewBindingFactory)
```

```
override fun getValue(thisRef: Fragment, property: KProperty<*>): T? {
        try {
            val binding = binding
            if (binding != null) {
                return binding
            }

            val lifecycle = fragment.viewLifecycleOwner.lifecycle
            if (!lifecycle.currentState.isAtLeast(Lifecycle.State.INITIALIZED)) {
                throw IllegalStateException("Should not attempt to get bindings when Fragment views are destroyed.")
            }

            return viewBindingFactory(thisRef.requireView()).also { this.binding = it }
        } catch (_: Exception) {
            return null
        }
    }
```

A simple change to the extension method and a try catch :)

**Comment by or-dvir-endios** [comment]
@osgu while this might solve the crash, it does not actually solve the problem (unless i misunderstood your comment) - cleaning up resources in `onDestroy`

the line `binding.recyclerView.adapter = null` would be converted to `binding?.recyclerView.adapter = null` (added `?` after `binding`).
so if `binding` is null, the cleanup code would not be executed

**Comment by Zhuinden** [comment]
@or-dvir-endios does the approach outlined in https://github.com/Zhuinden/fragmentviewbindingdelegate-kt/issues/12#issuecomment-812906086 not work for you?

**Comment by or-dvir** [comment]
> @or-dvir-endios does the approach outlined in [#12 (comment)](https://github.com/Zhuinden/fragmentviewbindingdelegate-kt/issues/12#issuecomment-812906086) not work for you?

technically it might work, but to me it beats the purpose of using this library so I am not using it...

**Comment by Zhuinden** [comment]
well yes, if you really want to use `onDestroyView` callback directly, then I advise using a nullable binding field

**Comment by rubensousa** [comment]
@Zhuinden 

I think we can leverage this internal behavior of fragments (which changed since this library was released I think): https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:fragment/fragment/src/main/java/androidx/fragment/app/FragmentStateManager.java;l=762-780?q=mViewLifecycleOwnerLiveData.setValue

The `mViewLifecycleOwnerLiveData` is cleared after `onDestroyView`, so we can use this fact to change the code as follows:

```kotlin
init {
    fragment.lifecycle.addObserver(object : DefaultLifecycleObserver {
        val viewLifecycleOwnerObserver = Observer<LifecycleOwner?> { owner ->
            if (owner == null) {
                binding = null
            }
        }
        override fun onCreate(owner: LifecycleOwner) {
            fragment.viewLifecycleOwnerLiveData.observeForever(viewLifecycleOwnerObserver)
        }

        override fun onDestroy(owner: LifecycleOwner) {
            fragment.viewLifecycleOwnerLiveData.removeObserver(viewLifecycleOwnerObserver)
        }
    })
}
```

**Comment by Zhuinden** [comment]
Wait, how does this alter the current code?

**Comment by rubensousa** [comment]
> Wait, how does this alter the current code?

The current code is:

```kotlin
init {
    fragment.lifecycle.addObserver(object : DefaultLifecycleObserver {
        val viewLifecycleOwnerLiveDataObserver = Observer<LifecycleOwner?> {
                val viewLifecycleOwner = it ?: return@Observer

                viewLifecycleOwner.lifecycle.addObserver(object : DefaultLifecycleObserver {
                    override fun onDestroy(owner: LifecycleOwner) {
                        binding = null
                    }
                })
            }

        override fun onCreate(owner: LifecycleOwner) {
            fragment.viewLifecycleOwnerLiveData.observeForever(viewLifecycleOwnerLiveDataObserver)
        }

        override fun onDestroy(owner: LifecycleOwner) {
            fragment.viewLifecycleOwnerLiveData.removeObserver(viewLifecycleOwnerLiveDataObserver)
        }
    })
}
```

Observing the `viewLifecycleOwner` directly will dispatch the `onDestroy` **before** the Fragment's `onDestroyView`. By the time the Fragment receives `onDestroyView`, the binding is already null.

However, if we observe the `viewLifecycleOwnerLiveData` and just react to the `owner` update, we get this **after** `onDestroyView`

This is the reason why:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/10662096/185473132-151dcf11-3ff0-44b5-896b-02b472f18f51.png">

**Comment by Zhuinden** [comment]
So the difference is `viewLifecycleOwner.lifecycle` vs `viewLifecycleOwnerLiveData`.

This change is less drastic than the one using FragmentLifecycleCallbacks, so it is now applied in 1.0.1.

Thank you @rubensousa for bringing this potential improvement to my attention

**Comment by Zhuinden** [comment]
If anyone sees any issues as a result of this change, please report as usual.
