### ISSUE TITLE
Failed to resolve: com.github.Zhuinden:fragmentviewbindingdelegate-kt:1.0.0

### ISSUE THREAD

**Issue by IanisT227** [Zhuinden/fragmentviewbindingdelegate-kt#21]
Hi! I am trying to use your library for a project. I did use it before and in that previous project it works just fine. However, for some reason, it seems like I cannot add it in any new project. I tried searching for anything useful, but nothing came up

**Comment by Zhuinden** [comment]
i presume it's because newer versions of Android Studio place the repositories in `settings.gradle` like this

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by IanisT227** [comment]
Yes, that was the issue! I did not manage to find anything related to it and that is why I opened the issue, thanks for your response!
