### ISSUE TITLE
[Bug]: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()

### ISSUE THREAD

**Issue by Drjacky** [Zhuinden/fragmentviewbindingdelegate-kt#3]
Rarely, and not sure how to reproduce it, I get "Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()" on line 63: "val lifecycle = fragment.viewLifecycleOwner.lifecycle".

**Comment by Zhuinden** [comment]
It's not a bug because you can't access the view before onCreateView and after onDestroyView.

Do the `val binding = binding` wherever you're using it in lifecycle callbacks and you should be good.

**Comment by mhmdcs** [comment]
If you're getting this error while collecting flows in a Fragment.

Use this extension function to safely collect them

```
fun <T> Flow<T>.safeCollection(lifecycleOwner: LifecycleOwner, data: suspend (T) -> Unit) {
    lifecycleOwner.lifecycleScope.launch {
        this@safeCollection.flowWithLifecycle(lifecycleOwner.lifecycle).collect {
            data(it)
        }
    }
}
```
Pass in getViewLifecycleOwner in the first parameter.

Further reading:
https://medium.com/androiddevelopers/a-safer-way-to-collect-flows-from-android-uis-23080b1f8bda
